# frozen_string_literal: true

require_relative 'lib/calc'

desc 'soma dois números'
task :sum, [:a, :b] do |_t, args|
  puts Calc.new(args).sum
end

desc 'subtrai dois números'
task :sub, [:a, :b] do |_t, args|
  puts Calc.new(args).sub
end

desc 'multiplica dois números'
task :mult, [:a, :b] do |_t, args|
  puts Calc.new(args).mult
end

desc 'divide dois números'
task :div, [:a, :b] do |_t, args|
  puts Calc.new(args).div
end
