# frozen_string_literal: true

require_relative 'lib/calc'

CALC_PARAMS = [:a, :b]

def calc(task, args)
  puts Calc.new(args).public_send(task.name)
end

desc 'soma dois números'
task(:sum, CALC_PARAMS, &method(:calc))

desc 'subtrai dois números'
task(:sub, CALC_PARAMS, &method(:calc))

desc 'multiplica dois números'
task(:mult, CALC_PARAMS, &method(:calc))

desc 'divide dois números'
task(:div, CALC_PARAMS, &method(:calc))
