# frozen_string_literal: true

require_relative 'lib/calc'

def calc(task, args)
  puts Calc.new(args).public_send(task.name)
end

desc 'soma dois números'
task(:sum, [:a, :b], &method(:calc))

desc 'subtrai dois números'
task(:sub, [:a, :b], &method(:calc))

desc 'multiplica dois números'
task(:mult, [:a, :b], &method(:calc))

desc 'divide dois números'
task(:div, [:a, :b], &method(:calc))
